"""/status probes, /metrics gating + format, JWT auto-generation, events cap."""

from types import SimpleNamespace

import pytest
from fastapi import HTTPException

from src.api import system as system_api
from src.configs.settings import get_settings
from src.services import metrics


@pytest.fixture(autouse=True)
def fresh(monkeypatch, tmp_path):
    metrics.reset()
    get_settings.cache_clear()
    monkeypatch.setenv("SUBAGENTS_MCP_TOKENS", str(tmp_path / "tokens.json"))
    yield
    metrics.reset()
    get_settings.cache_clear()


class _OkConn:
    async def __aenter__(self):
        return self

    async def __aexit__(self, *args):
        return False

    async def execute(self, q):
        return None


class _OkPool:
    def connection(self):
        return _OkConn()


class _DeadPool:
    def connection(self):
        raise RuntimeError("pool down")


class _OkRedis:
    async def ping(self):
        return True


class _DeadRedis:
    async def ping(self):
        raise ConnectionError("redis down")


class _OkQdrant:
    async def get_collections(self):
        return SimpleNamespace(collections=[])


def _request(db=None, redis=None, qdrant=None, mem0=None):
    state = SimpleNamespace(db=db or _OkPool(), redis=redis or _OkRedis(),
                            qdrant=qdrant or _OkQdrant(), mem0=mem0)
    return SimpleNamespace(app=SimpleNamespace(state=state))


async def test_status_all_healthy():
    result = await system_api.status(_request(mem0=object()), user_id="u1")
    assert result["postgres"] == {"ok": True}
    assert result["redis"] == {"ok": True}
    assert result["qdrant"] == {"ok": True}
    assert result["mem0"] is True
    assert "provider" in result["llm"]
    assert "providers" in result["mcp"]


async def test_status_dead_redis_still_returns_200_shape():
    result = await system_api.status(_request(redis=_DeadRedis()), user_id="u1")
    assert result["redis"]["ok"] is False
    assert "redis down" in result["redis"]["error"]
    assert result["postgres"]["ok"] is True  # other probes unaffected


async def test_status_dead_postgres():
    result = await system_api.status(_request(db=_DeadPool()), user_id="u1")
    assert result["postgres"]["ok"] is False


# ── /metrics ────────────────────────────────────────────────────────────────

async def test_metrics_404_when_no_token(monkeypatch):
    monkeypatch.setenv("METRICS_TOKEN", "")
    get_settings.cache_clear()
    with pytest.raises(HTTPException) as exc:
        await system_api.prometheus_metrics(credentials=None)
    assert exc.value.status_code == 404


async def test_metrics_401_on_wrong_token(monkeypatch):
    from fastapi.security import HTTPAuthorizationCredentials

    monkeypatch.setenv("METRICS_TOKEN", "right-token")
    get_settings.cache_clear()
    bad = HTTPAuthorizationCredentials(scheme="Bearer", credentials="wrong")
    with pytest.raises(HTTPException) as exc:
        await system_api.prometheus_metrics(credentials=bad)
    assert exc.value.status_code == 401


async def test_metrics_render_format(monkeypatch):
    from fastapi.security import HTTPAuthorizationCredentials

    monkeypatch.setenv("METRICS_TOKEN", "right-token")
    get_settings.cache_clear()
    metrics.inc("chat_turns_total")
    metrics.inc("chat_turns_total")
    good = HTTPAuthorizationCredentials(scheme="Bearer", credentials="right-token")
    text = await system_api.prometheus_metrics(credentials=good)
    assert "# TYPE subagents_chat_turns_total counter" in text
    assert "subagents_chat_turns_total 2" in text
    assert "subagents_llm_primary_up" in text


# ── JWT auto-generation ─────────────────────────────────────────────────────

def test_jwt_secret_autogenerated_and_stable(monkeypatch, tmp_path):
    from src.configs.settings import Settings

    secret_file = tmp_path / "jwt_secret"
    monkeypatch.setenv("SUBAGENTS_JWT_SECRET_FILE", str(secret_file))
    monkeypatch.setenv("AUTH_DISABLED", "false")
    monkeypatch.setenv("JWT_SECRET", "change-me-in-production")

    s1 = Settings()
    assert s1.jwt_secret != "change-me-in-production"
    assert len(s1.jwt_secret) >= 32
    assert secret_file.exists()
    assert (secret_file.stat().st_mode & 0o777) == 0o600
    # Stable across restarts.
    assert Settings().jwt_secret == s1.jwt_secret


def test_explicit_jwt_secret_wins(monkeypatch, tmp_path):
    from src.configs.settings import Settings

    monkeypatch.setenv("SUBAGENTS_JWT_SECRET_FILE", str(tmp_path / "jwt_secret"))
    monkeypatch.setenv("AUTH_DISABLED", "false")
    monkeypatch.setenv("JWT_SECRET", "my-real-secret-set-by-the-operator!")
    assert Settings().jwt_secret == "my-real-secret-set-by-the-operator!"
    assert not (tmp_path / "jwt_secret").exists()


# ── /events connection cap ──────────────────────────────────────────────────

async def test_events_connection_cap(monkeypatch):
    from src.api.events import events
    from src.services.event_broker import get_broker, reset_broker

    monkeypatch.setenv("EVENTS_MAX_CONNECTIONS_PER_USER", "2")
    get_settings.cache_clear()
    reset_broker()
    broker = get_broker()
    broker.subscribe("u1")
    broker.subscribe("u1")
    broker.subscribe("someone-else")  # other users don't count against u1

    with pytest.raises(HTTPException) as exc:
        await events(user_id="u1")
    assert exc.value.status_code == 429

    # A different user still connects fine.
    response = await events(user_id="u2")
    assert response is not None
    reset_broker()
